apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      name: manager
  template:
    metadata:
      labels:
        name: manager
    spec:
      containers:
      - name: manager
        image: quay.io/coreos/vault-operator:latest
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name